---
- name: "create user {{ nginx_user }}"
  user:
    become: true
    name: "{{ nginx_user }}"
    shell: /bin/nologin
    system: true

- name: download nginx-prometheus-exporter
  get_url:
    url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.4.0/nginx-prometheus-exporter-0.4.0-linux-amd64.tar.gz
    dest: /tmp/
    mode: 0644

- name: extract to /usr/local/bin
  become: true
  unarchive:
    src: /tmp/nginx-prometheus-exporter-0.4.0-linux-amd64.tar.gz
    dest: /usr/local/bin/nginx-prometheus-exporter/
    mode: 0644

- name: set nginx_exporter service
  become: true
  template:
    src: nginx_exporter.service.j2
    dest: /etc/systemd/system/nginx_exporter.service
    mode: 0644

- name: Starting and enabling nginx_exporter
  become: true
  service:
    name: nginx_exporter
    state: started
    enabled: true
