---
- name: "create user {{ nginx_user }}"
  become: true
  user:
    name: "{{ nginx_user }}"
    shell: /bin/nologin
    system: true

- name: download nginx-prometheus-exporter
  get_url:
    url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.4.0/nginx-prometheus-exporter-0.4.0-linux-amd64.tar.gz
    dest: /tmp/

- name: extract to /usr/local/bin/
  become: true
  unarchive:
    remote_src: true
    src: /tmp/nginx-prometheus-exporter-0.4.0-linux-amd64.tar.gz
    dest: /usr/local/bin/
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0750


- name: set nginx_exporter service
  become: true
  template:
    src: nginx_exporter.service.j2
    dest: /etc/systemd/system/nginx_exporter.service

- name: Starting and enabling nginx_exporter
  become: true
  service:
    name: nginx_exporter
    state: started
    enabled: true

- name: test port 9113 / metrics
  uri:
    url: "http://127.0.0.1:9113/metrics"
    method: GET
    return_content: true
  register: nginx_status
  failed_when: "'nginx_up 1' not in nginx_status.content"

- name: test port 80
  uri:
    url: "http://127.0.0.1"
    method: GET
    status_code: 200
